CREATE OR REPLACE PROCEDURE UPDATE_EMPLOYEE(
	   P_EMPLOYEE_ID IN TBL_EMPLEADO.ID%TYPE,
	   P_FECHANACI IN TBL_EMPLEADO.FECHANACI%TYPE,
	   P_NOMBRE IN TBL_EMPLEADO.NOMBRE%TYPE,
       P_SALARIO IN TBL_EMPLEADO.SALARIO%TYPE,
       P_ACTUALIZADO IN TBL_EMPLEADO.ACTUALIZADO%TYPE,
       P_DIAS_TRABAJADOS IN TBL_EMPLEADO.DIAS_TRABAJADOS%TYPE
)
IS
BEGIN

  UPDATE TBL_EMPLEADO 
  SET 
    FECHANACI = P_FECHANACI,
    NOMBRE = P_NOMBRE,
    SALARIO = P_SALARIO,
    ACTUALIZADO = P_ACTUALIZADO,
    DIAS_TRABAJADOS = P_DIAS_TRABAJADOS
  where ID = P_EMPLOYEE_ID;

  COMMIT;

END;
/